In [1]:
import pandas as pd
import numpy as np
from pathlib import Path
import soundfile as sf

E:\conda\envs\tf\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
E:\conda\envs\tf\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
E:\conda\envs\tf\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  stacklevel=1)


In [7]:
farend_speech_path='E:/intern/codes/dataset/farend_speech/'
nearend_speech_path='E:/intern/codes/dataset/nearend_speech/'
RIR_path='E:/intern/codes/dataset/RIR/'

In [16]:
fs=16000
time=4
len_of_samples=fs*time

In [8]:
farend_speechs=[]
for path in Path(farend_speech_path).rglob('*.wav'):
    farend_speechs.append(str(path.resolve()))
farend_speech_chunk_list=[]
for i in farend_speechs:
    audio,fs=sf.read(i)
    num_samples = int(np.fix(audio.shape[0]/len_of_samples))
    for j in range(num_samples):
        farend_speech_chunk_list.append(i+"{:02d}".format(j+1))

In [21]:
nearend_speechs=[]
for path in Path(nearend_speech_path).rglob('*.wav'):
    nearend_speechs.append(str(path.resolve()))
nearend_speech_chunk_list=[]
for i in nearend_speechs:
    audio,fs=sf.read(i)
    num_samples = int(np.fix(audio.shape[0]/len_of_samples))
    for j in range(num_samples):
        nearend_speech_chunk_list.append(i+"{:02d}".format(j+1))

In [26]:
Rirs=[]
for path in Path(RIR_path).rglob('*.wav'):
    Rirs.append(str(path.resolve()))

In [27]:
farend_speech_chunk_list

['E:\\intern\\codes\\dataset\\farend_speech\\farend_speech_fileid_0.wav01',
 'E:\\intern\\codes\\dataset\\farend_speech\\farend_speech_fileid_0.wav02',
 'E:\\intern\\codes\\dataset\\farend_speech\\farend_speech_fileid_1.wav01',
 'E:\\intern\\codes\\dataset\\farend_speech\\farend_speech_fileid_1.wav02',
 'E:\\intern\\codes\\dataset\\farend_speech\\farend_speech_fileid_10.wav01',
 'E:\\intern\\codes\\dataset\\farend_speech\\farend_speech_fileid_10.wav02',
 'E:\\intern\\codes\\dataset\\farend_speech\\farend_speech_fileid_100.wav01',
 'E:\\intern\\codes\\dataset\\farend_speech\\farend_speech_fileid_100.wav02',
 'E:\\intern\\codes\\dataset\\farend_speech\\farend_speech_fileid_1000.wav01',
 'E:\\intern\\codes\\dataset\\farend_speech\\farend_speech_fileid_1000.wav02']

In [28]:
nearend_speech_chunk_list

['E:\\intern\\codes\\dataset\\nearend_speech\\nearend_speech_fileid_0.wav01',
 'E:\\intern\\codes\\dataset\\nearend_speech\\nearend_speech_fileid_0.wav02',
 'E:\\intern\\codes\\dataset\\nearend_speech\\nearend_speech_fileid_1.wav01',
 'E:\\intern\\codes\\dataset\\nearend_speech\\nearend_speech_fileid_1.wav02',
 'E:\\intern\\codes\\dataset\\nearend_speech\\nearend_speech_fileid_10.wav01',
 'E:\\intern\\codes\\dataset\\nearend_speech\\nearend_speech_fileid_10.wav02',
 'E:\\intern\\codes\\dataset\\nearend_speech\\nearend_speech_fileid_100.wav01',
 'E:\\intern\\codes\\dataset\\nearend_speech\\nearend_speech_fileid_100.wav02',
 'E:\\intern\\codes\\dataset\\nearend_speech\\nearend_speech_fileid_1000.wav01',
 'E:\\intern\\codes\\dataset\\nearend_speech\\nearend_speech_fileid_1000.wav02']

In [29]:
Rirs

['E:\\intern\\codes\\dataset\\RIR\\large_room\\Room001-00001.wav',
 'E:\\intern\\codes\\dataset\\RIR\\large_room\\Room001-00002.wav',
 'E:\\intern\\codes\\dataset\\RIR\\large_room\\Room001-00005.wav',
 'E:\\intern\\codes\\dataset\\RIR\\large_room\\RVB2014_type1_rir_largeroom1_far_anglb.wav',
 'E:\\intern\\codes\\dataset\\RIR\\large_room\\RVB2014_type1_rir_largeroom1_near_angla.wav',
 'E:\\intern\\codes\\dataset\\RIR\\large_room\\RVB2014_type1_rir_largeroom2_far_anglb.wav',
 'E:\\intern\\codes\\dataset\\RIR\\small_room\\Room001-00001.wav',
 'E:\\intern\\codes\\dataset\\RIR\\small_room\\Room001-00003.wav']

In [30]:
np.save('meta/farend_speech_chunk_list',farend_speech_chunk_list)
np.save('meta/nearend_speech_chunk_list',nearend_speech_chunk_list)
np.save('meta/Rirs',Rirs)

In [31]:
np.random.choice([1,2,3,4],2)

array([2, 4])

In [2]:
import numpy as np

E:\conda\envs\tf\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
E:\conda\envs\tf\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
E:\conda\envs\tf\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  stacklevel=1)


In [10]:
rirs=np.load('meta/Rirs.npy')

In [11]:
rirs

array(['E:\\intern\\codes\\dataset\\RIR\\large_room\\Room001-00001.wav',
       'E:\\intern\\codes\\dataset\\RIR\\large_room\\Room001-00002.wav',
       'E:\\intern\\codes\\dataset\\RIR\\large_room\\Room001-00005.wav',
       'E:\\intern\\codes\\dataset\\RIR\\large_room\\RVB2014_type1_rir_largeroom1_far_anglb.wav',
       'E:\\intern\\codes\\dataset\\RIR\\large_room\\RVB2014_type1_rir_largeroom1_near_angla.wav',
       'E:\\intern\\codes\\dataset\\RIR\\large_room\\RVB2014_type1_rir_largeroom2_far_anglb.wav',
       'E:\\intern\\codes\\dataset\\RIR\\small_room\\Room001-00001.wav',
       'E:\\intern\\codes\\dataset\\RIR\\small_room\\Room001-00003.wav'],
      dtype='<U82')

In [12]:
selected_rirs=np.random.choice(rirs,2)

In [13]:
selected_rirs

array(['E:\\intern\\codes\\dataset\\RIR\\small_room\\Room001-00001.wav',
       'E:\\intern\\codes\\dataset\\RIR\\small_room\\Room001-00003.wav'],
      dtype='<U82')

In [14]:
nearend_rir, fs3=sf.read(selected_rirs[1])

In [15]:
nearend_rir.shape

(8000,)

In [16]:
def snr_cost(s_estimate, s_true):
    '''
    Static Method defining the cost function. 
    The negative signal to noise ratio is calculated here. The loss is 
    always calculated over the last dimension. 
    '''

    # calculating the SNR
    snr = tf.reduce_mean(tf.math.square(s_true), axis=-1, keepdims=True) / \
        (tf.reduce_mean(tf.math.square(s_true-s_estimate), axis=-1, keepdims=True)+1e-7)
    # using some more lines, because TF has no log10
    num = tf.math.log(snr) 
    denom = tf.math.log(tf.constant(10, dtype=num.dtype))
    loss = -10*(num / (denom))
    # returning the loss
    return loss

In [17]:
import tensorflow as tf

In [23]:
STD_n_db = np.random.uniform(-70,-120,1)
STD_n = 10**(STD_n_db/20)

In [24]:
np.log10(-20)

E:\conda\envs\tf\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log10
  """Entry point for launching an IPython kernel.


nan

In [25]:
STD_n

array([0.00029911])

In [26]:
np.random.normal(0, STD_n, nearend_rir.shape[0])

array([ 3.64157287e-05, -1.11502434e-04, -4.84049566e-05, ...,
        3.46211654e-05, -1.44443907e-04,  6.95125503e-04])